name: "Linear Traceability GitHub Action"
author: "Neo4j"
description: "Ensures pull requests are linked to a Linear issue"
branding:
  icon: 'award'
  color: 'green'
inputs:
  global_verification_strategy:
    required: false
    default: "commits"
    description: "One of comments, commits, title, disabled."
  github_api_token:
    required: true
    description: "API token for GitHub. Use GitHub secrets. Don't use plaintext."
runs:
  using: "node16"
  main: "dist/index.js"
