name: "Traceability GitHub Action"
author: "Daniel Leaver"
description: "Ensures git commit messages contain a Trello short link"
branding:
  icon: 'award'
  color: 'green'
inputs:
  global_verification_strategy:
    required: false
    default: "commits"
    description: "One of commits, commits_and_pr_title, disabled."
  short_link_verification_strategy:
    required: false
    default: "trello_or_noid"
    description: "One of trello, trello_or_noid."
  noid_short_link_pattern:
    required: false
    default: "\\[(NOID)\\]"
    description: "Regex pattern for the NOID short link."
  trello_api_key:
    required: true
    description: "API key for Trello. Use GitHub secrets. Don't use plaintext."
  trello_api_token:
    required: true
    description: "API token for Trello. Use GitHub secrets. Don't use plaintext."
  github_api_token:
    required: true
    description: "API token for GitHub. Use GitHub secrets. Don't use plaintext."
runs:
  using: "node16"
  main: "dist/index.js"
