"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERR_UNEXPECTED = exports.ERR_NO_SHORT_LINK = exports.ERR_NO_VALID_COMMENTS = exports.ERR_NO_LINEAR_ISSUE_TITLE_OR_DESCRIPTION = exports.ERR_INPUT_INVALID = exports.ERR_INPUT_NOT_FOUND = exports.ERR_INVALID_NOID = void 0;
const ERR_INVALID_NOID = (shortLinkId) => `Unexpected NOID short link "${shortLinkId}". Only Linear issue links are allowed in your project, please provide one in the form of "[TEAM-123] My change description".`;
exports.ERR_INVALID_NOID = ERR_INVALID_NOID;
const ERR_INPUT_NOT_FOUND = (input) => `Input not found "${input}".`;
exports.ERR_INPUT_NOT_FOUND = ERR_INPUT_NOT_FOUND;
const ERR_INPUT_INVALID = (input, value) => `Unrecognised value ${value} for input "${input}".`;
exports.ERR_INPUT_INVALID = ERR_INPUT_INVALID;
const ERR_NO_LINEAR_ISSUE_TITLE_OR_DESCRIPTION = () => `No Linear issue ID found in the PR title or description. Please include a Linear issue ID in the PR title using the format "[TEAM-123] My PR title", or include it anywhere in the PR description.`;
exports.ERR_NO_LINEAR_ISSUE_TITLE_OR_DESCRIPTION = ERR_NO_LINEAR_ISSUE_TITLE_OR_DESCRIPTION;
const ERR_NO_VALID_COMMENTS = () => `There were no comments in this PR that contained a valid Linear issue URL. This is likely either intentional or because you forgot to link this PR to a Linear issue. In order for this CI check to pass, you need to either link this PR to a Linear issue, or label your PR with the 'No Linear' label.`;
exports.ERR_NO_VALID_COMMENTS = ERR_NO_VALID_COMMENTS;
const ERR_NO_SHORT_LINK = (description) => `Description "${description}" did not contain a valid short link. Please include one like in the following examples: "[TEAM-123] My work description" or "[NOID] My work description".`;
exports.ERR_NO_SHORT_LINK = ERR_NO_SHORT_LINK;
const ERR_UNEXPECTED = (error) => `Unexpected: ${error}`;
exports.ERR_UNEXPECTED = ERR_UNEXPECTED;
