name: traceability-commits

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  traceability-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          global_verification_strategy: commits
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
