name: traceability-disabled

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  traceability-disabled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          global_verification_strategy: disabled
          github_api_token: "none"
