name: traceability-title

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  traceability-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          global_verification_strategy: title
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
