name: traceability

on:
  issue_comment: # // daniel document
    types:
      - created
      - edited
      - deleted

  pull_request:
    branches:
      - dev
    types:
      - labeled # // daniel document
      - unlabeled # // daniel document
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
              const requiredLabels = ['no release notes', 'public release notes'];
              let labels = [];

              if (context.payload.pull_request) {
                labels = context.payload.pull_request.labels;
              } else if (context.payload.issue) {
                labels = context.payload.issue.labels;
              }

              if (labels.filter(l => requiredLabels.includes(l.name)).length === 0) {
                throw new Error(`Required labels: ${requiredLabels.join(', ')}`);
              }
#      - uses: neo4j/github-action-traceability@v2
#        with:
#          trello_api_key: ${{ secrets.TRELLO_API_KEY }}
#          trello_api_token: ${{ secrets.TRELLO_API_TOKEN }}
#          github_api_token: ${{ secrets.GITHUB_TOKEN }}
