name: traceability-commits-and-title

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  traceability-commits-and-title:
    runs-on: ubuntu-latest
    steps:
      - uses: neo4j/github-action-traceability@v2
        with:
          global_verification_strategy: commits_and_pr_title
          trello_api_key: ${{ secrets.TRELLO_API_KEY }}
          trello_api_token: ${{ secrets.TRELLO_API_TOKEN }}
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository_owner: neo4j
          github_repository_name: github-action-traceability
          pull_request_number: ${{ github.event.pull_request.number }}
