name: traceability

on:
  issue_comment: # // daniel document
    types:
      - created
      - edited
      - deleted

  pull_request:
    branches:
      - dev
    types:
      - labeled # // daniel document
      - unlabeled # // daniel document
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        if: ${{ github.event.issue.pull_request }}
        run: |
          echo "hello world"
#      - name: do something???
#        id: request
#        uses: octokit/request-action@v2
#        with:
#          route: ${{ github.event.issue.pull_request.url }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: checkout pull request
#        uses: actions/checkout@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
#          ref: ${{ steps.pr_data.outputs.branch }}
#      - uses: neo4j/github-action-traceability@v2
#        with:
#          trello_api_key: ${{ secrets.TRELLO_API_KEY }}
#          trello_api_token: ${{ secrets.TRELLO_API_TOKEN }}
#          github_api_token: ${{ secrets.GITHUB_TOKEN }}
  pr-update:
    runs-on: ubuntu-latest
    steps:
      - uses: neo4j/github-action-traceability@v2
        with:
          trello_api_key: ${{ secrets.TRELLO_API_KEY }}
          trello_api_token: ${{ secrets.TRELLO_API_TOKEN }}
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
